### ISSUE TITLE
display the profile in distance rather than time?

### ISSUE THREAD

**Issue by beretor** [ThomasParistech/pretty-gpx#3]
Hello

2nd tiny feedback: I suspect the profile is displayed in duration rather than in distance? If this is the case, I would have expected the opposite?

See here

thanks a lot

<img width="530" alt="Screenshot 2024-09-11 at 15 44 51" src="https://github.com/user-attachments/assets/1d028a6c-bf9b-4e70-b6ef-9597706b37f7">

**Comment by ThomasParistech** [comment]
Hello

Yes I'm currently drawing the profile using the raw list of altitudes provided by the GPX.
It was a convenient solution, and since the profiles i've tested looked good, I never changed it. But it's on my to-do list! :wink:  

However, when handling multi-day hikes, I got the case where two GPX had a different sampling rate, and thus the profile looked terrible... The current solution handles this by allocating the daily profile interval width based on the actual distance. But it would be cleaner to deal directly with the cumulative distance

**Comment by ThomasParistech** [comment]
![image](https://github.com/user-attachments/assets/5ef5e110-cd28-440a-a4e3-2bd7fa20cc53)
I also need to remove one of the duplicates for the "col de la machine". There are both the hiking (1015m) and cycling (1011m) versions !

**Comment by beretor** [comment]
> Nice ride! 🔥
thanks !

> Yes I'm currently drawing the profile using the raw list of altitudes provided by the GPX. It was a convenient solution, and since the profiles i've tested looked good, I never changed it. But it's on my to-do list! 😉
Pretty big impact on steep climb (or for slow climbers ;-). On this example, i have climbed the steepest side of the col and it doesnt show up

**Comment by ThomasParistech** [comment]
Thanks to @JulesL2 
PR https://github.com/ThomasParistech/pretty-gpx/pull/6
