### ISSUE TITLE
[feature] Add a simplify GPX file option when loading GPX files

### ISSUE THREAD

**Issue by JulesL2** [ThomasParistech/pretty-gpx#5]
Hi,
As I do not know how to manage front-end, here is a bit of code that I use to simplify my gpx files so that my files can be processed by your wonderful package :). With distance=5m I do not lose a significant precision but my files goes from 20Mo to 1.5Mo :)

It uses only

If you can add this feature, it would be wonderful otherwise I cannot load my gpx files :)

```
import gpxpy 
import os
from pathlib import Path

def suffix_filename(filepath, suffix):
    """Add a suffix to a file path.

    Args:
        filepath (str): The file path.
        suffix (str): The suffix to add to the file path.

    Returns:
        str: The file path with the suffix added.
    """
    base, ext = os.path.splitext(filepath)
    return f"{base}{suffix}{ext}"

gpx_file = Path.cwd() / "myfile.gpx"
user_distance_value = 5

with open(gpx_file) as f:
    g = gpxpy.parse(f)

g.simplify(max_distance=user_distance_value)

with open(suffix_filename(gpx_file, "_simplified"), "w") as f:
    f.write(g.to_xml())
```

**Comment by ThomasParistech** [comment]
It seems like your issue is similar to this one: https://github.com/ThomasParistech/pretty-gpx/issues/2

There's an open github issue on the nicegui repo about potential fails with the ui.upload component https://github.com/zauberzeug/nicegui/issues/2918 ... You need to restart your browser and retry.

Unfortunately your snippet won't work because it fails before even opening the GPX, which is obviously required to call the simplify method! However we can add it as a stand-alone script to simplify a GPX, to somehow reduce the failure probability with a ligther file :smile: . That way you can run it before passing it to the webapp

**Comment by ThomasParistech** [comment]
What kind of race was it to weight 25Mo ? :smiley:

**Comment by JulesL2** [comment]
> What kind of race was it to weight 25Mo ? 😃

Wonderful poster with the program :)

![poster_Tour_des_stations](https://github.com/user-attachments/assets/fe57867a-3b97-4607-a5a4-325d8ff793a3)

**Comment by JulesL2** [comment]
> See commit [375bc72](https://github.com/ThomasParistech/pretty-gpx/commit/375bc7213a6bb9ded5d4fe19e6e1a6e8d4af2063)



> See commit [375bc72](https://github.com/ThomasParistech/pretty-gpx/commit/375bc7213a6bb9ded5d4fe19e6e1a6e8d4af2063)



> See commit [375bc72](https://github.com/ThomasParistech/pretty-gpx/commit/375bc7213a6bb9ded5d4fe19e6e1a6e8d4af2063)

Cool

**Comment by ThomasParistech** [comment]
Ok get it, it makes sense to add it as a pre-processing step then :+1:

**Comment by ThomasParistech** [comment]
Very nice! Feel free to play with the sun orientation and the color palettes :art:
